<?php
return array(
	'title'      => esc_html__( 'Logo Setting', 'povash' ),
	'id'         => 'logo_setting',
	'desc'       => '',
	'subsection' => false,
	'fields'     => array(
		array(
			'id'       => 'image_favicon',
			'type'     => 'media',
			'url'      => true,
			'title'    => esc_html__( 'Favicon', 'povash' ),
			'subtitle' => esc_html__( 'Insert site favicon image', 'povash' ),
			'default'  => array( 'url' => get_template_directory_uri() . '/assets/images/favicon.ico' ),
			//'required' => array( array( 'logo_type', 'equals', 'image' ) ),
		),
		array(
            'id' => 'normal_logo_show',
            'type' => 'switch',
            'title' => esc_html__('Enable Home One Logo', 'povash'),
            'default' => true,
        ),
		array(
			'id'       => 'image_normal_logo',
			'type'     => 'media',
			'url'      => true,
			'title'    => esc_html__( 'Home one Logo', 'povash' ),
			'subtitle' => esc_html__( 'Insert site Home One logo image', 'povash' ),
			'default'  => array( 'url' => get_template_directory_uri() . '/assets/images/logo.png' ),
			'required' => array( 'normal_logo_show', '=', true ),
		),
		array(
			'id'       => 'normal_logo_dimension',
			'type'     => 'dimensions',
			'title'    => esc_html__( 'Home one Logo Dimentions', 'povash' ),
			'subtitle' => esc_html__( 'Select Home one Logo Dimentions', 'povash' ),
			'units'    => array( 'em', 'px', '%' ),
			'default'  => array( 'Width' => '', 'Height' => '' ),
			'required' => array( 'normal_logo_show', '=', true ),
		),
		array(
            'id' => 'normal_logo_show2',
            'type' => 'switch',
            'title' => esc_html__('Enable Home one Mobile Logo', 'povash'),
            'default' => true,
        ),
		array(
			'id'       => 'image_normal_logo2',
			'type'     => 'media',
			'url'      => true,
			'title'    => esc_html__( 'Home One Mobile Logo', 'povash' ),
			'subtitle' => esc_html__( 'Insert site Home One Mobile logo image', 'povash' ),
			'default'  => array( 'url' => get_template_directory_uri() . '/assets/images/logo-2.png' ),
			'required' => array( 'normal_logo_show', '=', true ),
		),
		array(
			'id'       => 'normal_logo_dimension2',
			'type'     => 'dimensions',
			'title'    => esc_html__( 'Home One Mobile Logo Dimentions', 'povash' ),
			'subtitle' => esc_html__( 'Select Mobile Logo Dimentions', 'povash' ),
			'units'    => array( 'em', 'px', '%' ),
			'default'  => array( 'Width' => '', 'Height' => '' ),
			'required' => array( 'normal_logo_show', '=', true ),
		),
		array(
            'id' => 'normal_logo_show3',
            'type' => 'switch',
            'title' => esc_html__('Enable Home Two Logo', 'povash'),
            'default' => true,
        ),
		array(
			'id'       => 'image_normal_logo3',
			'type'     => 'media',
			'url'      => true,
			'title'    => esc_html__( 'Home Two Logo', 'povash' ),
			'subtitle' => esc_html__( 'Insert site Home Two logo image', 'povash' ),
			'default'  => array( 'url' => get_template_directory_uri() . '/assets/images/logo-v2.png' ),
			'required' => array( 'normal_logo_show', '=', true ),
		),
	
		array(
			'id'       => 'logo_settings_section_end',
			'type'     => 'section',
			'indent'      => false,
		),
	),
);
